### ISSUE TITLE
Npm refuses to install smartcrop-sharp as a dependency of itself

### ISSUE THREAD

**Issue by remborg** [jwagner/smartcrop-sharp#1]
On running `npm install smartcrop-sharp --save` on linux I get the following error :

```
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "smartcrop-sharp" "--save"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.3
npm ERR! code ENOSELF

npm ERR! Refusing to install smartcrop-sharp as a dependency of itself 
```

**Comment by jwagner** [comment]
Are you by any chance running this in the smartcrop-sharp repository? o.0

**Comment by remborg** [comment]
I was running it in a new directory (with clean package.json, freshly generated).
I didn't try it again but I think this issue can be closed, running `npm install smartcrop-sharp --save` in my current project worked perfectly :)
