### ISSUE TITLE
Upgrade Sharp peer dependency

### ISSUE THREAD

**Issue by nicholaschiang** [jwagner/smartcrop-sharp#16]
You're [requesting a really old sharp version](https://github.com/jwagner/smartcrop-sharp/blob/master/package.json#L15) (`0.25.3`) when the latest is at `0.28.0`.

I'd suggest updating that peer dependency in your `package.json`, rerunning some tests, and then releasing a new version on NPM.

**Comment by benayat** [comment]
to all others that face the same issue...is there a way to resolve this other then downgrade my sharp version? I'm not sure if I can count on update for 3 years old package...

**Comment by jwagner** [comment]
The easiest way to resolve the issue is to just copy the 50 lines of code in this package into your project or fork it. I plan to eventually update and typescript enable all of smartcrop but I have more work than capacity and it's just not one of my top priorities right now.

**Comment by jwagner** [comment]
Done in 2.0.4. :)
