### ISSUE TITLE
Missing link from NPM to this repo

### ISSUE THREAD

**Issue by ctaschereau** [jwagner/smartcrop-sharp#23]
When looking at the NPM page for this package (https://www.npmjs.com/package/smartcrop-sharp) , there is no link to this github repo.

I am not entirely familiar with how NPM hosting works, but I guess that the fix should be a simple config somewhere.

**Comment by jwagner** [comment]
Thanks for letting me know. Fixed it here: https://github.com/jwagner/smartcrop-sharp/commit/f39b5417e9af8c470795d0da62bebf7aa78cd3f0 :)
