### ISSUE TITLE
Update Sharp peer dependency

### ISSUE THREAD

**Issue by Enchiridion** [jwagner/smartcrop-sharp#27]
Hi, Could you please update the sharp dep to 0.31.2?  They fixed a bug where sharp would crash on certain png images on arm64 platforms.
Thanks!

**Comment by igorescobar** [comment]
https://github.com/jwagner/smartcrop-sharp/pull/28

**Comment by jwagner** [comment]
Update is in in 2.0.7. Sorry for the delay.

**Comment by Enchiridion** [comment]
Thank you!
