### ISSUE TITLE
Upgrade sharp version?

### ISSUE THREAD

**Issue by mikestopcontinues** [jwagner/smartcrop-sharp#4]
I ran into an interesting bug during deploy. Since my sharp dependency is more modern that smartcrop-sharp, somehow only smartcrop's sharp version was installed, breaking my deploy on netlify. This is a sharp issue, but I figured since it's a non-breaking change, it might be worth doing here as well.

**Comment by jwagner** [comment]
Will do that with the 2.0 release.
