### ISSUE TITLE
Can't upgrade to the latest version of sharp.

### ISSUE THREAD

**Issue by igorescobar** [jwagner/smartcrop-sharp#5]
When it's expected to support sharp v20.x?

**Comment by jwagner** [comment]
After a quick look at the changelog I don't see any reason why it would stop working. Could you provide the error that you are getting please?

**Comment by igorescobar** [comment]
There is no problem, I think the problem is with the way you define your
dependencies that are strict to the v0.19.x so we can't use v0.20 even
though it's working fine.

**Comment by igorescobar** [comment]
@jwagner I noticed that you changed your `package.json` but haven't bumped a new version to the `npm` repository.

**Comment by jwagner** [comment]
I started on it and then got distracted by something else while waiting for ci. I'll push it when I get home. It would be nice if sharp would go 1.0 one of these days so I could rely on the ^ semver.

**Comment by jwagner** [comment]
Released the new version as 2.0.3 now. This should fix your problem. :)
