### ISSUE TITLE
Request Deprecated 

### ISSUE THREAD

**Issue by vin-ni** [jwagner/smartcrop-sharp#7]
As of Feb 11th 2020, request is fully deprecated.
https://www.npmjs.com/package/request

What would be an alternative to use?

**Comment by jwagner** [comment]
Probably just the core http library or axios. I haven't done much with node.js recently so I'm quite out of touch. If I find a bit of time I'll adjust the examples to use the core http package.

**Comment by jwagner** [comment]
@vin-ni I updated the readme now and added a test showing how to use the standard http package. What do you think?

**Comment by vin-ni** [comment]
Looks good!
I'll give it a try :)
Thank you!
